services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: vocal-royale-backend
    container_name: vocal-royale-backend
    ports:
      # Map host BACKEND_PORT → container 8080 (PocketBase)
      - "${BACKEND_PORT:-8090}:${BACKEND_PORT:-8090}"
    volumes:
      # Persist PocketBase data on the host
      - pb_data:/pb/pb_data
    restart: unless-stopped

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: vocal-royale-app
    container_name: vocal-royale-app
    env_file:
      - compose.env
    ports:
      - "${APP_PORT:-5173}:${APP_PORT:-5173}"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pb_data:
