#!/usr/bin/env sh
set -e

# Ins app-Verzeichnis wechseln und dort lint-staged laufen lassen
cd "$(git rev-parse --show-toplevel)/app"

# Nur gestagte Dateien in app/ formatieren/linten
npx lint-staged