name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: app
            context: ./app
            file: ./app/Dockerfile
            repo: aja30-app
          - name: backend
            context: ./backend
            file: ./backend/Dockerfile
            repo: aja30-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (PR) ${{ matrix.name }}
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          load: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.repo }}:pr-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push (main) ${{ matrix.name }}
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.repo }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.repo }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
